# -*- coding: utf-8 -*-
"""Projek SISPAK .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fyh6DHia6kPyf9_frvExHTUD19ry0d6j
"""

import pandas as pd
df = pd.read_csv('hepatitis_csv.csv')
df.head()

df = df.dropna()
df.head()

from sklearn import preprocessing 
le = preprocessing.LabelEncoder()

df['steroid'] = le.fit_transform(df['steroid']) 
df['antivirals'] = le.fit_transform(df['antivirals']) 
df['fatigue'] = le.fit_transform(df['fatigue']) 
df['malaise'] = le.fit_transform(df['malaise']) 
df['anorexia'] = le.fit_transform(df['anorexia']) 
df['liver_big'] = le.fit_transform(df['liver_big']) 
df['liver_firm'] = le.fit_transform(df['liver_firm']) 
df['spleen_palpable'] = le.fit_transform(df['spleen_palpable'])
df['spiders'] = le.fit_transform(df['spiders'])
df['ascites'] = le.fit_transform(df['ascites'])
df['varices'] = le.fit_transform(df['varices'])
df['varices'] = le.fit_transform(df['varices'])
df['histology'] = le.fit_transform(df['histology'])
df['kondisi'] = le.fit_transform(df['class'])

df.head()

df.drop (['age','sex','class'],inplace=True,axis=1)

df.info()

"""**DECISION TREE**"""

from sklearn.tree import DecisionTreeClassifier
from sklearn import metrics
from sklearn.model_selection import train_test_split

xdata = df.drop('kondisi',axis=1)
ydata = df.kondisi

xtrain,xtest,ytrain,ytest=train_test_split (xdata,ydata,test_size=0.2, random_state=1)

clf = DecisionTreeClassifier()
clf = clf.fit(xtrain,ytrain)

ypred = clf.predict(xtest)
ypred

print('Akurasi DTREE = ',metrics.accuracy_score(ytest,ypred)*100)

"""**NAIVE BAYES**"""

import numpy as np

xdata = df.drop('kondisi',axis=1)
ydata = df.kondisi 

ydata

xtrain,xtest,ytrain,ytest=train_test_split (xdata,ydata,test_size=0.3, random_state=1)

from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
nbtrain = gnb.fit(xtest,ytest)
ymodel=gnb.fit(xtest,ytest)

print('Akurasi NAIVE BAYES = ',metrics.accuracy_score(ytest,ypred)*100)